export { default as day1 } from './day1.js'
export { default as day2 } from './day2.js'
export { default as day3 } from './day3.js'
export { default as day4 } from './day4.js'
export { default as day5 } from './day5.js'
export { default as day6 } from './day6.js'
